"""AI research scientist loop over the Research Lab MCP server.

The LLM researches, hypothesizes and interprets. This controller (plain code) owns:
  * campaign creation and geometry setup (no LLM turn spent on them);
  * the hard caps: LLM turns, tool calls, experiments;
  * gating run_experiment on the deterministic planner: only its proposed parameters run,
    and nothing runs once it says stop / cannot_plan;
  * the report's measured tables, built from the store via MCP -- never from LLM text.

Run:  python -m research_lab.agent --geometry path/to/part.step [--question "..."]
LLM: RESEARCH_LLM_PROVIDER (groq | anthropic, see llm.py). Web research: the server's RESEARCH_PROVIDER.
"""

from __future__ import annotations

import argparse
import asyncio
import json
import os
import sys
from datetime import datetime, timezone
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Callable

from research_lab.llm import LLMError, LLMProvider, ToolResult, llm_from_env

CONTROLLER_TOOLS = {"create_campaign", "setup_geometry"}  # not offered to the LLM

SYSTEM = """You are the research scientist of an automated computational lab. You investigate a \
meshing question for one CAD geometry using tools. Flowlab (a Gmsh meshing service) produces every \
measurement; you never produce or alter measurements.

Research discipline:
- Use search_evidence, then fetch_source (with keywords) on the most authoritative hits, then \
record_evidence with a verbatim excerpt from fetched text. If search is unsupported, fetch_source \
URLs of primary sources you know (e.g. official tool documentation). The gate decides admissibility; \
report it as given. Retrieval errors are not evidence.
- Classify each claim: metric_relevance (a metric is appropriate), metric_definition (what it means), \
numerical_threshold (a specific value). Record a numerical_threshold only when the excerpt states the number.
- If no admissible source states a threshold, say so plainly and use the user-supplied demo objective \
with threshold_basis="demo". Never present a demo threshold as a sourced fact.
- Be economical: at most 3 searches and 4 fetches in total.

Experiment discipline:
- Fix the objective once with fix_objective, before any experiment.
- Before each experiment call plan_next_experiment. The planner is authoritative: run only its \
next_parameters, and stop experimenting when it says stop or cannot_plan.
- Every run_experiment needs a falsifiable hypothesis and a rationale.
- After each result call record_interpretation (what changed, what it means, next decision). \
Quote only numbers that appear in tool results.
- Outcomes: ok = measured quality data; failed = this configuration failed (no quality data, do not \
guess why); refused = fix the request, not a measurement; infra_error / unresolved = no information \
about the mesh.
- This lab does verification (mesh criteria) only. There is no solver: make no claim of physical validation.

When experimentation has stopped, reply with a final summary (no tool call) using these headings: \
Hypothesis, Evidence assessment, Interpretation, Limitations. Tables of measurements are generated by code."""


# --- compaction: what the LLM sees of tool results -------------------------------------

def _round(x: Any) -> Any:
    if isinstance(x, float):
        return float(f"{x:.4g}")
    if isinstance(x, dict):
        return {k: _round(v) for k, v in x.items()}
    if isinstance(x, list):
        return [_round(v) for v in x]
    return x


def _experiment_view(e: dict) -> dict:
    r = e["result"]
    return {"experiment_id": e["experiment_id"], "parameters": e["parameters"], "outcome": r["outcome"],
            "generation_id": r["generation_id"], "element_count": r["element_count"],
            "node_count": r["node_count"],
            "metrics": {m: {s: v[s] for s in ("min", "mean", "max")} for m, v in r["metrics"].items()},
            "findings": len(r["findings"]), "error_code": r["error_code"], "feasible": r["feasible"],
            "feasibility_reason": r["feasibility_reason"], "bounding_box": r["bounding_box"]}


def compact(name: str, out: dict) -> dict:
    if "error" in out:
        return out
    if name == "run_experiment":
        return {"outcome": out["outcome"], "repeat": out["repeat"], **_experiment_view(out["experiment"]),
                **({"planner_after": out["planner_after"]} if "planner_after" in out else {})}
    if name == "get_campaign":
        c = out["campaign"]
        return {"campaign": {k: c[k] for k in ("id", "question", "objective", "objective_basis", "search",
                                               "max_experiments", "geometry")},
                "budget_used": out["budget_used"], "experiments": [_experiment_view(e) for e in out["experiments"]],
                "evidence": [{k: e[k] for k in ("id", "claim_kind", "claim", "admissibility")} for e in out["evidence"]]}
    if name == "compare_experiments":
        return {k: v for k, v in out.items() if k != "history"}
    return out


def serialize(name: str, out: dict, max_chars: int) -> str:
    """The LLM-facing text of a tool result. The result object itself is never modified."""
    view = _round(compact(name, out))
    if name == "fetch_source" and "passages" in view:
        view = {**view, "passages": [p[:600] for p in view["passages"][:4]]}
    if name == "search_evidence" and "results" in view:
        view = {**view, "results": [{k: (v[:200] if k == "snippet" else v) for k, v in h.items()
                                     if k in ("title", "url", "snippet", "tier", "source_type")}
                                    for h in view["results"]]}
    text = json.dumps(view, sort_keys=True)
    return text if len(text) <= max_chars else text[:max_chars] + " ...[truncated]"


def _summary(name: str, out: dict) -> Any:
    """Short activity-log view of a result."""
    if "error" in out:
        return {"error": out["error"]}
    if name == "run_experiment":
        e = out["experiment"]
        return {"experiment_id": e["experiment_id"], "outcome": out["outcome"], "repeat": out["repeat"],
                "generation_id": e["result"]["generation_id"], "element_count": e["result"]["element_count"],
                "feasible": e["result"]["feasible"], "planner_after": out.get("planner_after")}
    if name == "search_evidence":
        return {"results": [{"title": h["title"], "url": h["url"], "tier": h["tier"]} for h in out["results"]]}
    if name == "fetch_source":
        return {k: out.get(k) for k in ("url", "title", "status", "tier", "total_chars")}
    if name == "record_evidence":
        return {k: out.get(k) for k in ("id", "claim_kind", "admissibility", "gate_reasons")}
    if name == "plan_next_experiment":
        return _decision_view(out) if "status" in out else out
    return {"ok": True}


def fit_history(history: list[dict], budget: int) -> None:
    """Elide the oldest tool results (then long old assistant text) until the history fits.
    The latest tool results are never elided; the store holds everything in full."""
    def size() -> int:
        n = 0
        for h in history:
            if h["role"] == "user":
                n += len(h["text"])
            elif h["role"] == "assistant":
                n += len(h["turn"].text) + sum(len(json.dumps(c.arguments or {})) + 40 for c in h["turn"].tool_calls)
            else:
                n += sum(len(r.content) for r in h["results"])
        return n
    olds = [h for h in history[:-1] if h["role"] == "tool_results"]
    for h in olds:
        if size() <= budget:
            return
        for r in h["results"]:
            if not r.content.startswith('{"elided"'):
                r.content = json.dumps({"elided": True, "tool": r.name, "head": r.content[:120]})
    for h in history[:-1]:
        if size() <= budget:
            return
        if h["role"] == "assistant" and len(h["turn"].text) > 300:
            h["turn"].text = h["turn"].text[:300] + " ...[elided]"


def _slim(schema: Any) -> Any:
    """LLM-facing schema: drop titles, and turn optional `anyOf [X, null]` into plain X (optional by
    not being required). Smaller, and weaker models stop sending explicit nulls."""
    if isinstance(schema, dict):
        alts = schema.get("anyOf")
        if isinstance(alts, list) and len(alts) == 2 and {"type": "null"} in alts:
            other = next(x for x in alts if x != {"type": "null"})
            rest = {k: v for k, v in schema.items() if k not in ("anyOf", "default")}
            return _slim({**other, **rest})
        return {k: _slim(v) for k, v in schema.items() if k != "title"}
    if isinstance(schema, list):
        return [_slim(v) for v in schema]
    return schema


# Arguments the controller requires even where the MCP tool makes them optional.
REQUIRED_FOR_AGENT = {"run_experiment": {"hypothesis": "A falsifiable prediction about this experiment's result.",
                                         "rationale": "Why this experiment tests it (cite the planner proposal)."}}


def llm_schema(name: str, schema: dict) -> dict:
    s = _slim(schema)
    extra = REQUIRED_FOR_AGENT.get(name)
    if extra:
        props = {**s.get("properties", {}),
                 **{k: {"type": "string", "minLength": 10, "description": d} for k, d in extra.items()}}
        s = {**s, "properties": props, "required": sorted(set(s.get("required", [])) | set(extra))}
    return s


def _decision_view(d: dict) -> dict:
    return {k: d[k] for k in ("status", "reason", "next_parameters", "best_feasible", "bracket", "budget", "notes")}


# --- controller ------------------------------------------------------------------------

@dataclass
class Limits:
    max_llm_turns: int = 30
    max_tool_calls: int = 60
    max_experiments: int = 5
    max_result_chars: int = 3000   # one serialized tool result, as sent to the LLM
    history_chars: int = 4000      # older tool results are elided past this (ITPM-limited providers)


@dataclass
class AgentRun:
    campaign_id: str | None = None
    stop_reason: str = "not_started"
    llm_turns: int = 0
    tool_calls: int = 0
    experiments_run: int = 0
    final_text: str | None = None
    planner_log: list[dict] = field(default_factory=list)
    refused_calls: list[dict] = field(default_factory=list)


class Controller:
    def __init__(self, session: Any, llm: LLMProvider, limits: Limits = Limits(),
                 on_event: Callable[[dict], None] | None = None):
        self.session, self.llm, self.limits, self.on_event = session, llm, limits, on_event
        self.run = AgentRun()

    def _event(self, kind: str, **data) -> None:
        if self.on_event is not None:
            self.on_event({"kind": kind, "turn": self.run.llm_turns, **data})

    async def call(self, name: str, args: dict) -> dict:
        r = await self.session.call_tool(name, args)
        if r.is_error:
            return {"error": {"kind": "tool_error", "message": r.content[0].text if r.content else ""}}
        return r.structured_content

    async def plan(self) -> dict:
        d = await self.call("plan_next_experiment", {"campaign_id": self.run.campaign_id})
        view = _decision_view(d) if "status" in d else d
        self.run.planner_log.append(view)
        self._event("planner", decision=view)
        return d

    async def dispatch(self, name: str, args: dict) -> dict:
        self.run.tool_calls += 1
        if self.run.tool_calls > self.limits.max_tool_calls:
            return {"error": {"kind": "limit", "message": "tool call limit reached; write the final summary"}}
        if name not in self.allowed:
            self.run.refused_calls.append({"tool": name, "reason": "not an available tool"})
            return {"error": {"kind": "unknown_tool", "message": f"{name} is not available"}}
        args = {**args, "campaign_id": self.run.campaign_id}
        if name == "run_experiment":
            gate = await self._gate_experiment(args)
            if gate is not None:
                self.run.refused_calls.append({"tool": name, "reason": gate["error"]["kind"]})
                return gate
            out = await self.call(name, args)
            if "error" not in out and not out.get("repeat"):
                self.run.experiments_run += 1
            if "error" not in out:
                out["planner_after"] = _decision_view(await self.plan())
            return out
        return await self.call(name, args)

    async def _gate_experiment(self, args: dict) -> dict | None:
        if not str(args.get("hypothesis") or "").strip() or not str(args.get("rationale") or "").strip():
            return {"error": {"kind": "invalid_arguments", "message": "hypothesis and rationale must be non-empty "
                              "strings, e.g. {\"parameters\": {...planner next_parameters...}, \"hypothesis\": "
                              "\"...\", \"rationale\": \"...\"}"}}
        if self.run.experiments_run >= self.limits.max_experiments:
            return {"error": {"kind": "experiment_limit", "message": "agent experiment limit reached"}}
        d = await self.plan()
        if d.get("status") != "propose":
            return {"error": {"kind": "planner_refused", "decision": _decision_view(d) if "status" in d else d}}
        if args.get("parameters") != d["next_parameters"]:
            return {"error": {"kind": "parameters_not_planned", "message": "run the planner's next_parameters",
                              "expected": d["next_parameters"]}}
        return None

    async def research(self, question: str, setup: dict, brief: str) -> AgentRun:
        c = await self.call("create_campaign", {"question": question, "max_experiments": self.limits.max_experiments})
        if "error" in c:
            self.run.stop_reason = f"create_campaign_failed:{c['error']['kind']}"
            return self.run
        self.run.campaign_id = c["campaign_id"]
        self._event("campaign_created", campaign_id=self.run.campaign_id, question=question)
        return await self.research_existing(self.run.campaign_id, question, setup, brief)

    async def research_existing(self, campaign_id: str, question: str, setup: dict, brief: str) -> AgentRun:
        """Run the loop for an already-created campaign (UI path reuses this).

        setup_geometry still runs inside the loop so geometry upload goes
        through the existing MCP tool + Flowlab client, not a second pipeline.
        """
        self.run.campaign_id = campaign_id
        g = await self.call("setup_geometry", {"campaign_id": campaign_id, **setup})
        if "error" in g:
            self.run.stop_reason = f"setup_geometry_failed:{g['error']['kind']}"
            self._event("stopped", reason=self.run.stop_reason, error=g["error"])
            return self.run
        self._event("geometry_ready", geometry=g["geometry"], source=Path(setup["geometry_path"]).name)

        listed = (await self.session.list_tools()).tools
        tools = sorted(({"name": t.name, "description": t.description or "", "input_schema": llm_schema(t.name, t.input_schema)}
                        for t in listed if t.name not in CONTROLLER_TOOLS), key=lambda t: t["name"])
        self.allowed = {t["name"] for t in tools}
        history: list[dict] = [{"role": "user", "text": (
            f"Research question: {question}\n\nCampaign: {self.run.campaign_id} (geometry is set up: "
            f"{json.dumps(g['geometry'])}; declared units {setup['length_unit']}, {setup['up_axis']}-up; "
            f"the bounding box is reported with the first mesh).\n\n{brief}")}]

        self.run.stop_reason = "turn_limit"
        while self.run.llm_turns < self.limits.max_llm_turns:
            self.run.llm_turns += 1
            try:
                turn = self.llm.step(SYSTEM, tools, history)
            except LLMError as e:
                self.run.stop_reason = f"llm_error: {e}"[:300]
                break
            history.append({"role": "assistant", "turn": turn})
            if turn.text:
                self._event("agent_text", text=turn.text[:2000])
            if turn.stop == "refusal":
                self.run.stop_reason = "llm_refusal"
                break
            if not turn.tool_calls:
                self.run.final_text = turn.text
                self.run.stop_reason = "agent_finished" if turn.stop == "end" else f"llm_{turn.stop}"
                break
            results = []

            # Planning is a controller barrier. If the LLM asks for a new
            # plan and also tries to run an experiment in the same turn,
            # the experiment must wait until the next LLM turn. Otherwise
            # the model can execute stale parameters before it has seen the
            # planner's newly proposed parameters.
            has_planner_call = any(
                call.name == "plan_next_experiment" for call in turn.tool_calls
            )

            terminal_planner = False

            for call in turn.tool_calls:
                if has_planner_call and call.name == "run_experiment":
                    out = {
                        "error": {
                            "kind": "planner_barrier",
                            "message": (
                                "A new planner proposal was requested in this "
                                "turn. Do not run an experiment yet; inspect "
                                "the planner result and run its exact "
                                "next_parameters on the next turn."
                            ),
                        }
                    }
                elif call.arguments is None:
                    self.run.tool_calls += 1
                    out = {"error": {"kind": "invalid_arguments", "message": call.parse_error}}
                else:
                    out = await self.dispatch(call.name, call.arguments)

                if (
                    call.name == "plan_next_experiment"
                    and isinstance(out, dict)
                    and out.get("status") in {"stop", "cannot_plan"}
                ):
                    terminal_planner = True
                    self.run.stop_reason = (
                        f"planner_{out['status']}:{out.get('reason', '')}"
                    )[:300]

                self._event(
                    "tool",
                    tool=call.name,
                    arguments=call.arguments,
                    result=_summary(call.name, out),
                )
                results.append(
                    ToolResult(
                        call.id,
                        serialize(call.name, out, self.limits.max_result_chars),
                        "error" in out,
                        call.name,
                    )
                )

                if terminal_planner:
                    break

            history.append({"role": "tool_results", "results": results})

            if terminal_planner:
                break

            fit_history(history, self.limits.history_chars)
        self._event("stopped", reason=self.run.stop_reason, llm_turns=self.run.llm_turns)
        return self.run


# --- report: measured tables come from the store, text sections are labeled ------------

def _fmt_metrics(metrics: dict) -> str:
    return "; ".join(f"{m} min {v['min']:.4g} / mean {v['mean']:.4g}" for m, v in sorted(metrics.items())) or "—"


def render_report(run: AgentRun, state: dict, summary: dict, final_decision: dict) -> str:
    c, exps, evid, notes = state["campaign"], state["experiments"], state["evidence"], state["notes"]
    L = [f"# Research report — campaign {c['id']}", "",
         "Labels: **[SOURCED]** retrieved evidence passed by the gate · **[MEASURED]** Flowlab/Gmsh output · "
         "**[AGENT]** LLM hypothesis/interpretation · **[DEMO ASSUMPTION]** user-supplied, unsupported", "",
         "## Research question", c["question"], "", "## Evidence"]
    if not evid:
        L.append("No evidence was recorded.")
    for e in evid:
        label = "[SOURCED]" if e["admissibility"] == "admissible" else f"[{e['admissibility'].upper()}]"
        s = e["source"]
        L += [f"- **{e['id']}** {label} ({e['claim_kind']}) {e['claim']}",
              f"  - source: {s.get('title') or s['url']} — {s['url']} (tier {s['tier']}, {s['source_type']}"
              f"{', publisher ' + s['publisher'] if s.get('publisher') else ''})",
              f"  - excerpt ({e['retrieved_via']}, verified={e['excerpt_verified']}): \"{e['excerpt']}\"",
              f"  - applicability [AGENT]: {e['applicability']}",
              f"  - gate: {'; '.join(e['gate_reasons'])}"]
    obj = c["objective"]
    basis = c.get("objective_basis") or "—"
    tag = "[DEMO ASSUMPTION]" if basis.startswith("demo") else "[SOURCED]"
    L += ["", "## Objective and unsupported assumptions",
          f"- objective: fewest elements subject to {obj['metric']}.{obj['stat']} ≥/≤ {obj['threshold']} "
          f"(direction from Flowlab's metric orientation) — {tag} {basis}" if obj else "- no objective fixed",
          f"- search: {c['search']}" if c.get("search") else "- no search range",
          "", "## Hypotheses [AGENT]"]
    L += [f"- {e['experiment_id']}: {e['hypothesis']}" for e in exps] or ["- none"]
    L += ["", "## Experiments [MEASURED]",
          "| experiment | parameters | generation | outcome | elements | nodes | metrics | feasible | Flowlab reused |",
          "|---|---|---|---|---|---|---|---|---|"]
    for e in exps:
        r = e["result"]
        L.append(f"| {e['experiment_id']} | `{json.dumps(e['parameters'])}` | {r['generation_id'] or '—'} | "
                 f"{r['outcome']}{' (' + r['error_code'] + ')' if r['error_code'] else ''} | "
                 f"{r['element_count'] if r['element_count'] is not None else '—'} | "
                 f"{r['node_count'] if r['node_count'] is not None else 'not reported'} | "
                 f"{_fmt_metrics(r['metrics'])} | {r['feasible']} | {e.get('flowlab_existing')} |")
    L += ["", "## Observed changes [MEASURED]"]
    for p in summary.get("consecutive", []):
        if p.get("comparable"):
            ec = p["element_count"]
            ms = "; ".join(f"{m}.{s} {d['from']:.4g}→{d['to']:.4g}" for m, st in p["metrics"].items()
                           for s, d in st.items() if s in ("min", "mean") and d)
            L.append(f"- {p['from']} → {p['to']} {p['changed_parameters']}: elements {ec['from']}→{ec['to']} "
                     f"({ec['abs']:+d}); {ms}")
    t = summary.get("trend", {})
    L.append(f"- trend over {t.get('parameter')}: {t.get('status')}"
             + (": " + ", ".join(f"{k} {v['direction']}" for k, v in t["series"].items()) if t.get("status") == "ok" else ""))
    L += ["", "## Interpretation [AGENT]"]
    L += [f"- {n['experiment_id']}: {n['interpretation']}" for n in notes] or ["- none recorded"]
    L += ["", "## Next-experiment decisions",
          *[f"- [AGENT] after {n['experiment_id']}: {n['next_decision']}" for n in notes],
          *[f"- [PLANNER] {d.get('status')} {d.get('reason')} next={d.get('next_parameters')}" for d in run.planner_log],
          "", "## Stopping reason",
          f"- planner: {final_decision.get('status')} — {final_decision.get('reason')} "
          f"(best feasible: {final_decision.get('best_feasible')}, bracket {final_decision.get('bracket')})",
          f"- loop: {run.stop_reason}; LLM turns {run.llm_turns}, tool calls {run.tool_calls}, "
          f"experiments executed {run.experiments_run}",
          *([f"- refused agent calls: {run.refused_calls}"] if run.refused_calls else []),
          "", "## Agent summary [AGENT]", run.final_text or "(no final summary produced)",
          "", "## Limitations",
          "- Verification only: mesh-quality criteria on one geometry. No solver, so no physical validation.",
          "- One varied parameter (target_element_size); other mesh settings pinned at Flowlab defaults.",
          "- Feasibility uses one metric statistic; worst-element statistics are sensitive to single elements.",
          "- node_count is not reported by Flowlab and is never inferred.",
          "- Evidence tiers are assigned by host name; an admissible source can still be inapplicable to this workflow."]
    return "\n".join(L) + "\n"


async def finish(controller: Controller) -> tuple[str, dict]:
    cid = controller.run.campaign_id
    state = await controller.call("get_campaign", {"campaign_id": cid})
    summary = await controller.call("compare_experiments", {"campaign_id": cid})
    final = await controller.call("plan_next_experiment", {"campaign_id": cid})
    return render_report(controller.run, state, summary, final), state


# --- CLI -------------------------------------------------------------------------------

def _brief(demo: str, search: str) -> str:
    metric, stat, thr = demo.split(":")
    lo, hi, tol = search.split(",")
    return (f"User-supplied demo objective (not evidence): fewest elements subject to metric=\"{metric}\", "
            f"stat=\"{stat}\", threshold={thr}; search target_element_size in [{lo}, {hi}] with "
            f"rel_tolerance {tol}; no pinned_parameters. Call fix_objective with exactly these values and "
            f"threshold_basis=\"demo\" unless admissible evidence states a threshold for this metric.")


async def amain(a: argparse.Namespace) -> int:
    from mcp.client import Client
    from mcp.client.stdio import StdioServerParameters
    params = StdioServerParameters(command=sys.executable, args=["-m", "research_lab.mcp_server"],
                                   env={**os.environ, "RESEARCH_LAB_STORE": a.store})
    try:
        llm = llm_from_env(model=a.model)  # fails fast if the selected provider is not configured
    except LLMError as e:
        print(f"LLM not configured: {e}", file=sys.stderr)
        return 2
    def log(event: dict) -> None:  # live activity feed for the UI; agent-side state only
        cid = event.get("campaign_id") or (ctl.run.campaign_id if ctl else None)
        if cid:
            with open(Path(a.store) / cid / "activity.jsonl", "a") as f:
                f.write(json.dumps({"at": datetime.now(timezone.utc).isoformat(), **event}, default=str) + "\n")
        print(f"[{event['kind']}] {json.dumps({k: v for k, v in event.items() if k != 'kind'}, default=str)[:240]}",
              file=sys.stderr)

    ctl = None
    async with Client(params) as session:
        ctl = Controller(session, llm, Limits(a.max_turns, 60, a.max_experiments), on_event=log)
        run = await ctl.research(a.question, {"geometry_path": a.geometry, "length_unit": a.length_unit,
                                              "up_axis": a.up_axis}, _brief(a.demo_objective, a.search))
        if run.campaign_id is None:
            print(f"aborted: {run.stop_reason}", file=sys.stderr)
            return 1
        report, _ = await finish(ctl)
    out = Path(a.store) / run.campaign_id / "report.md"
    (Path(a.store) / run.campaign_id / "run.json").write_text(json.dumps(
        {"stop_reason": run.stop_reason, "llm_turns": run.llm_turns, "tool_calls": run.tool_calls,
         "experiments_run": run.experiments_run, "llm": f"{llm.name}/{llm.model}",
         "geometry_source": Path(a.geometry).name}, indent=2))
    out.write_text(report)
    usage = {k: sum(u.get(k, 0) for u in llm.usage) for k in ("input", "output", "cache_read", "cache_write")}
    print(report)
    print(f"report: {out}\nLLM {llm.name}/{llm.model} usage: {usage}", file=sys.stderr)
    return 0


def load_dotenv(path: Path = Path(".env")) -> None:
    """KEY=VALUE lines into os.environ; existing variables win. Values are never printed."""
    if not path.is_file():
        return
    for line in path.read_text().splitlines():
        line = line.strip()
        if line and not line.startswith("#") and "=" in line:
            k, v = line.removeprefix("export ").split("=", 1)
            os.environ.setdefault(k.strip(), v.strip().strip('"').strip("'"))


def main() -> None:
    load_dotenv()
    p = argparse.ArgumentParser()
    p.add_argument("--question", default="How does mesh resolution affect mesh quality for this geometry, "
                   "and what mesh resolution provides an appropriate trade-off between mesh quality and element count?")
    p.add_argument("--geometry", required=True, help="CAD file uploaded unmodified to Flowlab (step/iges/stl/obj/msh)")
    p.add_argument("--length-unit", default="mm")
    p.add_argument("--up-axis", default="z")
    p.add_argument("--demo-objective", default="minSICN:min:0.005", help="metric:stat:threshold (unsupported demo)")
    p.add_argument("--search", default="6,12,0.1", help="lower,upper,rel_tolerance for target_element_size")
    p.add_argument("--store", default="campaigns")
    p.add_argument("--model", default=None, help="override the provider's configured model")
    p.add_argument("--max-turns", type=int, default=30)
    p.add_argument("--max-experiments", type=int, default=5)
    sys.exit(asyncio.run(amain(p.parse_args())))


if __name__ == "__main__":
    main()
